<a href="https://colab.research.google.com/github/ushnamalik207-dotcom/code-switching-codesaviours-si26-ushna/blob/main/SI_Week7_Ushna_Alam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Step 2 & 3: Authentic Code-Switching Dataset Collection (150+ Sentences)
data = [
    {'sentence': 'Aaj ka din bohot busy tha, had 3 meetings back to back',
     'words': ['Aaj', 'ka', 'din', 'bohot', 'busy', 'tha,', 'had', '3', 'meetings', 'back', 'to', 'back'],
     'labels': ['URD', 'URD', 'URD', 'URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Yaar seriously I can not even right now, bohot thak gaya hoon',
     'words': ['Yaar', 'seriously', 'I', 'can', 'not', 'even', 'right', 'now,', 'bohot', 'thak', 'gaya', 'hoon'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'URD']},
    {'sentence': 'Bhai kal mera presentation hai, still not prepared at all',
     'words': ['Bhai', 'kal', 'mera', 'presentation', 'hai,', 'still', 'not', 'prepared', 'at', 'all'],
     'labels': ['URD', 'URD', 'URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Mera laptop freeze ho gaya hai, need to restart it',
     'words': ['Mera', 'laptop', 'freeze', 'ho', 'gaya', 'hai,', 'need', 'to', 'restart', 'it'],
     'labels': ['URD', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Assignment submit kar di hai, huge relief for me',
     'words': ['Assignment', 'submit', 'kar', 'di', 'hai,', 'huge', 'relief', 'for', 'me'],
     'labels': ['ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Chai break chahiye, my brain is completely dead now',
     'words': ['Chai', 'break', 'chahiye,', 'my', 'brain', 'is', 'completely', 'dead', 'now'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Kal weather bohot awesome hone wala hai, perfect for trip',
     'words': ['Kal', 'weather', 'bohot', 'awesome', 'hone', 'wala', 'hai,', 'perfect', 'for', 'trip'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Internet connection slow chal raha hai, speed test kar lo',
     'words': ['Internet', 'connection', 'slow', 'chal', 'raha', 'hai,', 'speed', 'test', 'kar', 'lo'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Traffic Jam tha, was stuck in traffic for 2 hours',
     'words': ['Traffic', 'Jam', 'tha,', 'was', 'stuck', 'in', 'traffic', 'for', '2', 'hours'],
     'labels': ['ENG', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Coffee peene ka mood hai, let us go out',
     'words': ['Coffee', 'peene', 'ka', 'mood', 'hai,', 'let', 'us', 'go', 'out'],
     'labels': ['ENG', 'URD', 'URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Is question ka answer mil gaya hai, thanks for help',
     'words': ['Is', 'question', 'ka', 'answer', 'mil', 'gaya', 'hai,', 'thanks', 'for', 'help'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Class timing cancel ho gayi hai, brilliant news',
     'words': ['Class', 'timing', 'cancel', 'ho', 'gayi', 'hai,', 'brilliant', 'news'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Phone ki battery dead ho gayi hai, charger kahan hai',
     'words': ['Phone', 'ki', 'battery', 'dead', 'ho', 'gayi', 'hai,', 'charger', 'kahan', 'hai'],
     'labels': ['ENG', 'URD', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'URD', 'URD']},
    {'sentence': 'Procrastination ki waja se pending work ki list lambi ho gayi',
     'words': ['Procrastination', 'ki', 'waja', 'se', 'pending', 'work', 'ki', 'list', 'lambi', 'ho', 'gayi'],
     'labels': ['ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG', 'URD', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Weekend mood unlocked, let us enjoy the day',
     'words': ['Weekend', 'mood', 'unlocked,', 'let', 'us', 'enjoy', 'the', 'day'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Exam hall mein mind totally blank ho gaya tha',
     'words': ['Exam', 'hall', 'mein', 'mind', 'totally', 'blank', 'ho', 'gaya', 'tha'],
     'labels': ['ENG', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Gym workout ke baad body ache ho raha hai',
     'words': ['Gym', 'workout', 'ke', 'baad', 'body', 'ache', 'ho', 'raha', 'hai'],
     'labels': ['ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Fast food order kar lete hain, I am so hungry',
     'words': ['Fast', 'food', 'order', 'kar', 'lete', 'hain,', 'I', 'am', 'so', 'hungry'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Is product ka review kaisa hai, please share feedback',
     'words': ['Is', 'product', 'ka', 'review', 'kaisa', 'hai,', 'please', 'share', 'feedback'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'URD', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Notification alert silent par tha, missed your call',
     'words': ['Notification', 'alert', 'silent', 'par', 'tha,', 'missed', 'your', 'call'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Online shopping se delivery time par aa gayi',
     'words': ['Online', 'shopping', 'se', 'delivery', 'time', 'par', 'aa', 'gayi'],
     'labels': ['ENG', 'ENG', 'URD', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Movie scene bohot emotional tha, made me cry',
     'words': ['Movie', 'scene', 'bohot', 'emotional', 'tha,', 'made', 'me', 'cry'],
     'labels': ['ENG', 'ENG', 'URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'New update install kar liya hai, smooth UI hai',
     'words': ['New', 'update', 'install', 'kar', 'liya', 'hai,', 'smooth', 'UI', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Project ka deadline extended ho gaya hai, great news',
     'words': ['Project', 'ka', 'deadline', 'extended', 'ho', 'gaya', 'hai,', 'great', 'news'],
     'labels': ['ENG', 'URD', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Focus mode on karke study start karte hain',
     'words': ['Focus', 'mode', 'on', 'karke', 'study', 'start', 'karte', 'hain'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Password change karna hai, account security issue tha',
     'words': ['Password', 'change', 'karna', 'hai,', 'account', 'security', 'issue', 'tha'],
     'labels': ['ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Night drive par chalte hain, weather is amazing today',
     'words': ['Night', 'drive', 'par', 'chalte', 'hain,', 'weather', 'is', 'amazing', 'today'],
     'labels': ['ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Subah early morning wake up routine tough lag raha hai',
     'words': ['Subah', 'early', 'morning', 'wake', 'up', 'routine', 'tough', 'lag', 'raha', 'hai'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Song beat drop bohot powerful tha, loved the music',
     'words': ['Song', 'beat', 'drop', 'bohot', 'powerful', 'tha,', 'loved', 'the', 'music'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Group chat Mute kar do, too many notifications',
     'words': ['Group', 'chat', 'Mute', 'kar', 'do,', 'too', 'many', 'notifications'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'WiFi router restart karo, connection loss lag raha hai',
     'words': ['WiFi', 'router', 'restart', 'karo,', 'connection', 'loss', 'lag', 'raha', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Is problem ka solution simple hai, easy steps follow karo',
     'words': ['Is', 'problem', 'ka', 'solution', 'simple', 'hai,', 'easy', 'steps', 'follow', 'karo'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Ghar pohench kar message karunga, stay safe',
     'words': ['Ghar', 'pohench', 'kar', 'message', 'karunga,', 'stay', 'safe'],
     'labels': ['URD', 'URD', 'URD', 'ENG', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Cricket match ka tension hai, need win today',
     'words': ['Cricket', 'match', 'ka', 'tension', 'hai,', 'need', 'win', 'today'],
     'labels': ['ENG', 'ENG', 'URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'New recipe try karni hai, sounds delicious',
     'words': ['New', 'recipe', 'try', 'karni', 'hai,', 'sounds', 'delicious'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Rainy season start ho gaya hai, beautiful atmosphere',
     'words': ['Rainy', 'season', 'start', 'ho', 'gaya', 'hai,', 'beautiful', 'atmosphere'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Zoom call schedule change kar do, I am busy',
     'words': ['Zoom', 'call', 'schedule', 'change', 'kar', 'do,', 'I', 'am', 'busy'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Software bug fix kar diya hai, issue resolved',
     'words': ['Software', 'bug', 'fix', 'kar', 'diya', 'hai,', 'issue', 'resolved'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Coffee mug break ho gaya, sad moment for me',
     'words': ['Coffee', 'mug', 'break', 'ho', 'gaya,', 'sad', 'moment', 'for', 'me'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Presentation slide clean aur clear hai, good work',
     'words': ['Presentation', 'slide', 'clean', 'aur', 'clear', 'hai,', 'good', 'work'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'ENG', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Direct Message karo, personal query hai',
     'words': ['Direct', 'Message', 'karo,', 'personal', 'query', 'hai'],
     'labels': ['ENG', 'ENG', 'URD', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Bohot dino baad outdoor sports khela, feeling refreshed',
     'words': ['Bohot', 'dino', 'baad', 'outdoor', 'sports', 'khela,', 'feeling', 'refreshed'],
     'labels': ['URD', 'URD', 'URD', 'ENG', 'ENG', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Document print kar ke sign kar do',
     'words': ['Document', 'print', 'kar', 'ke', 'sign', 'kar', 'do'],
     'labels': ['ENG', 'ENG', 'URD', 'URD', 'ENG', 'URD', 'URD']},
    {'sentence': 'Shopping Mall mein sales offers chal rahe hain',
     'words': ['Shopping', 'Mall', 'mein', 'sales', 'offers', 'chal', 'rahe', 'hain'],
     'labels': ['ENG', 'ENG', 'URD', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Is movie ki ending ka Suspense unexpected tha',
     'words': ['Is', 'movie', 'ki', 'ending', 'ka', 'Suspense', 'unexpected', 'tha'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'URD', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Drive slowly, road condition bohot rough hai',
     'words': ['Drive', 'slowly,', 'road', 'condition', 'bohot', 'rough', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'ENG', 'URD']},
    {'sentence': 'Bhai link share kar do, urgently open karna hai',
     'words': ['Bhai', 'link', 'share', 'kar', 'do,', 'urgently', 'open', 'karna', 'hai'],
     'labels': ['URD', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'System crash ho gaya, lost all my unsaved work',
     'words': ['System', 'crash', 'ho', 'gaya,', 'lost', 'all', 'my', 'unsaved', 'work'],
     'labels': ['ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Teatime discussion always productive hoti hai',
     'words': ['Teatime', 'discussion', 'always', 'productive', 'hoti', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Ghar ki decoration bohot aesthetic lag rahi hai',
     'words': ['Ghar', 'ki', 'decoration', 'bohot', 'aesthetic', 'lag', 'rahi', 'hai'],
     'labels': ['URD', 'URD', 'ENG', 'URD', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Is device ki Performance top class hai',
     'words': ['Is', 'device', 'ki', 'Performance', 'top', 'class', 'hai'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Headache ho raha hai, need rest right now',
     'words': ['Headache', 'ho', 'raha', 'hai,', 'need', 'rest', 'right', 'now'],
     'labels': ['ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Weather forecast rain predict kar raha hai',
     'words': ['Weather', 'forecast', 'rain', 'predict', 'kar', 'raha', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Is post ko Share aur Like zaroor karna',
     'words': ['Is', 'post', 'ko', 'Share', 'aur', 'Like', 'zaroor', 'karna'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'URD', 'ENG', 'URD', 'URD']},
    {'sentence': 'Time management bohot important factor hai',
     'words': ['Time', 'management', 'bohot', 'important', 'factor', 'hai'],
     'labels': ['ENG', 'ENG', 'URD', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Office meeting 10 baje start ho gi',
     'words': ['Office', 'meeting', '10', 'baje', 'start', 'ho', 'gi'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'ENG', 'URD', 'URD']},
    {'sentence': 'Apne views aur feedback section mein comment karain',
     'words': ['Apne', 'views', 'aur', 'feedback', 'section', 'mein', 'comment', 'karain'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'URD', 'ENG', 'URD']},
    {'sentence': 'Flight delay hone ki waja se wait karna para',
     'words': ['Flight', 'delay', 'hone', 'ki', 'waja', 'se', 'wait', 'karna', 'para'],
     'labels': ['ENG', 'ENG', 'URD', 'URD', 'URD', 'URD', 'ENG', 'URD', 'URD']},
    {'sentence': 'New laptop specs bohot high-end hain',
     'words': ['New', 'laptop', 'specs', 'bohot', 'high-end', 'hain'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'MIX', 'URD']},
    {'sentence': 'Aapka response bohot helpful tha, thank you',
     'words': ['Aapka', 'response', 'bohot', 'helpful', 'tha,', 'thank', 'you'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Power outage ki waja se work disturb ho gaya',
     'words': ['Power', 'outage', 'ki', 'waja', 'se', 'work', 'disturb', 'ho', 'gaya'],
     'labels': ['ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Code logic correct hai, syntax error fixed',
     'words': ['Code', 'logic', 'correct', 'hai,', 'syntax', 'error', 'fixed'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Is video ka Content informative aur engaging hai',
     'words': ['Is', 'video', 'ka', 'Content', 'informative', 'aur', 'engaging', 'hai'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'URD', 'ENG', 'URD']},
    {'sentence': 'Ghar mein load-shedding chal rahi hai, no light',
     'words': ['Ghar', 'mein', 'load-shedding', 'chal', 'rahi', 'hai,', 'no', 'light'],
     'labels': ['URD', 'URD', 'MIX', 'URD', 'URD', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Study plan ready hai, tomorrow implementation hoga',
     'words': ['Study', 'plan', 'ready', 'hai,', 'tomorrow', 'implementation', 'hoga'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Social media breaks zaruri hain for Mental health',
     'words': ['Social', 'media', 'breaks', 'zaruri', 'hain', 'for', 'Mental', 'health'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Is hotel ka service Quality impressive tha',
     'words': ['Is', 'hotel', 'ka', 'service', 'Quality', 'impressive', 'tha'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Key features verify kar lo pehle',
     'words': ['Key', 'features', 'verify', 'kar', 'lo', 'pehle'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Audio quality bohot clear hai, crisp sound',
     'words': ['Audio', 'quality', 'bohot', 'clear', 'hai,', 'crisp', 'sound'],
     'labels': ['ENG', 'ENG', 'URD', 'ENG', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Data Backup create kar do, just in case',
     'words': ['Data', 'Backup', 'create', 'kar', 'do,', 'just', 'in', 'case'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Team discussion successful rahi, progress on track',
     'words': ['Team', 'discussion', 'successful', 'rahi,', 'progress', 'on', 'track'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Car repair charges extra lag gaye hain',
     'words': ['Car', 'repair', 'charges', 'extra', 'lag', 'gaye', 'hain'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Fresh juice order kar do, healthy option',
     'words': ['Fresh', 'juice', 'order', 'kar', 'do,', 'healthy', 'option'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Mera schedule fully packed hai, zero free time',
     'words': ['Mera', 'schedule', 'fully', 'packed', 'hai,', 'zero', 'free', 'time'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Security guidelines carefully read kar lo',
     'words': ['Security', 'guidelines', 'carefully', 'read', 'kar', 'lo'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Ghar ke pass Park open ho gaya hai',
     'words': ['Ghar', 'ke', 'pass', 'Park', 'open', 'ho', 'gaya', 'hai'],
     'labels': ['URD', 'URD', 'URD', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Online payment successful ho gayi hai',
     'words': ['Online', 'payment', 'successful', 'ho', 'gayi', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Exam tension khatam, complete relax mode',
     'words': ['Exam', 'tension', 'khatam,', 'complete', 'relax', 'mode'],
     'labels': ['ENG', 'ENG', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Is course ke modules well organized hain',
     'words': ['Is', 'course', 'ke', 'modules', 'well', 'organized', 'hain'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Movie tickets book ho gayi hain, see you tonight',
     'words': ['Movie', 'tickets', 'book', 'ho', 'gayi', 'hain,', 'see', 'you', 'tonight'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Apne workspace ko clean aur organize rakho',
     'words': ['Apne', 'workspace', 'ko', 'clean', 'aur', 'organize', 'rakho'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'URD', 'ENG', 'URD']},
    {'sentence': 'Fitness tracking app daily install karke use karo',
     'words': ['Fitness', 'tracking', 'app', 'daily', 'install', 'karke', 'use', 'karo'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'ENG', 'URD']},
    {'sentence': 'Bohot thand hai, hot coffee best option hai',
     'words': ['Bohot', 'thand', 'hai,', 'hot', 'coffee', 'best', 'option', 'hai'],
     'labels': ['URD', 'URD', 'URD', 'ENG', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Project presentation next week schedule hui hai',
     'words': ['Project', 'presentation', 'next', 'week', 'schedule', 'hui', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'New mobile camera features impressive hain',
     'words': ['New', 'mobile', 'camera', 'features', 'impressive', 'hain'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Fast internet connection is a basic necessity now',
     'words': ['Fast', 'internet', 'connection', 'is', 'a', 'basic', 'necessity', 'now'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Ghar ka interior design minimalistic aur modern hai',
     'words': ['Ghar', 'ka', 'interior', 'design', 'minimalistic', 'aur', 'modern', 'hai'],
     'labels': ['URD', 'URD', 'ENG', 'ENG', 'ENG', 'URD', 'ENG', 'URD']},
    {'sentence': 'Team lead feedback positive tha, good start',
     'words': ['Team', 'lead', 'feedback', 'positive', 'tha,', 'good', 'start'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Shopping bill unexpected high aaya hai',
     'words': ['Shopping', 'bill', 'unexpected', 'high', 'aaya', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Night stay at friend place was full of fun',
     'words': ['Night', 'stay', 'at', 'friend', 'place', 'was', 'full', 'of', 'fun'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Ghar mein renovation work chal raha hai',
     'words': ['Ghar', 'mein', 'renovation', 'work', 'chal', 'raha', 'hai'],
     'labels': ['URD', 'URD', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Is restaurant ka ambience bohot chill hai',
     'words': ['Is', 'restaurant', 'ka', 'ambience', 'bohot', 'chill', 'hai'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'URD', 'ENG', 'URD']},
    {'sentence': 'File download speed bohot fast thi, completed',
     'words': ['File', 'download', 'speed', 'bohot', 'fast', 'thi,', 'completed'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'ENG', 'URD', 'ENG']},
    {'sentence': 'System software crash ho gaya, restart needed',
     'words': ['System', 'software', 'crash', 'ho', 'gaya,', 'restart', 'needed'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Meeting links email pe send kar diye hain',
     'words': ['Meeting', 'links', 'email', 'pe', 'send', 'kar', 'diye', 'hain'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Mera daily goal achieve ho gaya hai',
     'words': ['Mera', 'daily', 'goal', 'achieve', 'ho', 'gaya', 'hai'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'New song album release hui hai, check out',
     'words': ['New', 'song', 'album', 'release', 'hui', 'hai,', 'check', 'out'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Ghar ke paas Gym join kar liya hai',
     'words': ['Ghar', 'ke', 'paas', 'Gym', 'join', 'kar', 'liya', 'hai'],
     'labels': ['URD', 'URD', 'URD', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Task assignment list email kar di hai',
     'words': ['Task', 'assignment', 'list', 'email', 'kar', 'di', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Coffee mug refill kar do, long night study hai',
     'words': ['Coffee', 'mug', 'refill', 'kar', 'do,', 'long', 'night', 'study', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Mera phone screen replacement hona hai',
     'words': ['Mera', 'phone', 'screen', 'replacement', 'hona', 'hai'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Is course ke certificates valid hain for job',
     'words': ['Is', 'course', 'ke', 'certificates', 'valid', 'hain', 'for', 'job'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Weekend gateway trip set hai, super excited',
     'words': ['Weekend', 'gateway', 'trip', 'set', 'hai,', 'super', 'excited'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'ENG', 'ENG']},
    {'sentence': 'Class notes share kar do, missing today lecture',
     'words': ['Class', 'notes', 'share', 'kar', 'do,', 'missing', 'today', 'lecture'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Ghar mein family dinner hai, late aunga',
     'words': ['Ghar', 'mein', 'family', 'dinner', 'hai,', 'late', 'aunga'],
     'labels': ['URD', 'URD', 'ENG', 'ENG', 'URD', 'ENG', 'URD']},
    {'sentence': 'Mera laptop heating issue show kar raha hai',
     'words': ['Mera', 'laptop', 'heating', 'issue', 'show', 'kar', 'raha', 'hai'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Online order tracking updates check karo',
     'words': ['Online', 'order', 'tracking', 'updates', 'check', 'karo'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Weather cloudy hai, rain prediction heavy hai',
     'words': ['Weather', 'cloudy', 'hai,', 'rain', 'prediction', 'heavy', 'hai'],
     'labels': ['ENG', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'New design pattern trial basis par chal raha hai',
     'words': ['New', 'design', 'pattern', 'trial', 'basis', 'par', 'chal', 'raha', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'URD']},
    {'sentence': 'Data storage clean up karna padega',
     'words': ['Data', 'storage', 'clean', 'up', 'karna', 'padega'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Group study plan delay ho gaya hai',
     'words': ['Group', 'study', 'plan', 'delay', 'ho', 'gaya', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Is game ka graphics level top tier hai',
     'words': ['Is', 'game', 'ka', 'graphics', 'level', 'top', 'tier', 'hai'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Shopping bag drop kar do room mein',
     'words': ['Shopping', 'bag', 'drop', 'kar', 'do', 'room', 'mein'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'URD']},
    {'sentence': 'System memory full ho gayi hai, delete unwanted files',
     'words': ['System', 'memory', 'full', 'ho', 'gayi', 'hai,', 'delete', 'unwanted', 'files'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Ghar ka wifi password reset karna hai',
     'words': ['Ghar', 'ka', 'wifi', 'password', 'reset', 'karna', 'hai'],
     'labels': ['URD', 'URD', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Mera subscription plan renew ho gaya hai',
     'words': ['Mera', 'subscription', 'plan', 'renew', 'ho', 'gaya', 'hai'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Traffic update check karke nikalna',
     'words': ['Traffic', 'update', 'check', 'karke', 'nikalna'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Car washing schedule pending par hai',
     'words': ['Car', 'washing', 'schedule', 'pending', 'par', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Is project ki progress report submit kar di hai',
     'words': ['Is', 'project', 'ki', 'progress', 'report', 'submit', 'kar', 'di', 'hai'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Morning workout session bohot energetic tha',
     'words': ['Morning', 'workout', 'session', 'bohot', 'energetic', 'tha'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'ENG', 'URD']},
    {'sentence': 'Is website ka UI/UX design clean lag raha hai',
     'words': ['Is', 'website', 'ka', 'UI/UX', 'design', 'clean', 'lag', 'raha', 'hai'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Fresh coffee spill ho gayi desk par',
     'words': ['Fresh', 'coffee', 'spill', 'ho', 'gayi', 'desk', 'par'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'ENG', 'URD']},
    {'sentence': 'Class presentation feedback overwhelmingly positive tha',
     'words': ['Class', 'presentation', 'feedback', 'overwhelmingly', 'positive', 'tha'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Night study routine set kar liya hai',
     'words': ['Night', 'study', 'routine', 'set', 'kar', 'liya', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Mera phone silent mode par pada tha',
     'words': ['Mera', 'phone', 'silent', 'mode', 'par', 'pada', 'tha'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Online shopping delivery on time mil gayi',
     'words': ['Online', 'shopping', 'delivery', 'on', 'time', 'mil', 'gayi'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Is software ka installation setup easy tha',
     'words': ['Is', 'software', 'ka', 'installation', 'setup', 'easy', 'tha'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Team lead meeting post-pone ho gayi hai',
     'words': ['Team', 'lead', 'meeting', 'post-pone', 'ho', 'gayi', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'System update restart expect kar raha hai',
     'words': ['System', 'update', 'restart', 'expect', 'kar', 'raha', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Ghar ke security camera online hain',
     'words': ['Ghar', 'ke', 'security', 'camera', 'online', 'hain'],
     'labels': ['URD', 'URD', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Mera assignment review pending list mein hai',
     'words': ['Mera', 'assignment', 'review', 'pending', 'list', 'mein', 'hai'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Weekend trip planning start karni hai',
     'words': ['Weekend', 'trip', 'planning', 'start', 'karni', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'New book reading goal set kar liya hai',
     'words': ['New', 'book', 'reading', 'goal', 'set', 'kar', 'liya', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Cricket match live streaming dekh rahe hain',
     'words': ['Cricket', 'match', 'live', 'streaming', 'dekh', 'rahe', 'hain'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Ghar ka renovation budget exceed ho gaya',
     'words': ['Ghar', 'ka', 'renovation', 'budget', 'exceed', 'ho', 'gaya'],
     'labels': ['URD', 'URD', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Fast food cravings control karni padengi',
     'words': ['Fast', 'food', 'cravings', 'control', 'karni', 'padengi'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'System performance benchmark clear ho gaya',
     'words': ['System', 'performance', 'benchmark', 'clear', 'ho', 'gaya'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Coffee machine repair ke liye bhej di hai',
     'words': ['Coffee', 'machine', 'repair', 'ke', 'liye', 'bhej', 'di', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'URD', 'URD']},
    {'sentence': 'Class schedule cancel hone ki khabar mili hai',
     'words': ['Class', 'schedule', 'cancel', 'hone', 'ki', 'khabar', 'mili', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD', 'URD', 'URD']},
    {'sentence': 'Mera laptop battery backup improve ho gaya',
     'words': ['Mera', 'laptop', 'battery', 'backup', 'improve', 'ho', 'gaya'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Social media Detox plan activate kar diya',
     'words': ['Social', 'media', 'Detox', 'plan', 'activate', 'kar', 'diya'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Weather forecast clear sky show kar raha hai',
     'words': ['Weather', 'forecast', 'clear', 'sky', 'show', 'kar', 'raha', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Group meeting time extend ho gaya hai',
     'words': ['Group', 'meeting', 'time', 'extend', 'ho', 'gaya', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Ghar mein tea party arrange ki hai',
     'words': ['Ghar', 'mein', 'tea', 'party', 'arrange', 'ki', 'hai'],
     'labels': ['URD', 'URD', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Mera daily target complete ho gaya hai',
     'words': ['Mera', 'daily', 'target', 'complete', 'ho', 'gaya', 'hai'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Online webinar attendance mark ho gayi hai',
     'words': ['Online', 'webinar', 'attendance', 'mark', 'ho', 'gayi', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Shopping Mall parking full ho gayi thi',
     'words': ['Shopping', 'Mall', 'parking', 'full', 'ho', 'gayi', 'thi'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'New mobile cover order kar diya hai',
     'words': ['New', 'mobile', 'cover', 'order', 'kar', 'diya', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'File compression complete ho gayi hai',
     'words': ['File', 'compression', 'complete', 'ho', 'gayi', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Mera morning walk routine skip ho gaya',
     'words': ['Mera', 'morning', 'walk', 'routine', 'skip', 'ho', 'gaya'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Is product ki packaging high level thi',
     'words': ['Is', 'product', 'ki', 'packaging', 'high', 'level', 'thi'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Traffic signal stop par waiting time lamba tha',
     'words': ['Traffic', 'signal', 'stop', 'par', 'waiting', 'time', 'lamba', 'tha'],
     'labels': ['ENG', 'ENG', 'ENG', 'URD', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Ghar mein quiet environment needed hai',
     'words': ['Ghar', 'mein', 'quiet', 'environment', 'needed', 'hai'],
     'labels': ['URD', 'URD', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Mera phone screen timeout adjust karna hai',
     'words': ['Mera', 'phone', 'screen', 'timeout', 'adjust', 'karna', 'hai'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Is course ke practice sets useful hain',
     'words': ['Is', 'course', 'ke', 'practice', 'sets', 'useful', 'hain'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Night sky viewing experience peaceful tha',
     'words': ['Night', 'sky', 'viewing', 'experience', 'peaceful', 'tha'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'System reboot karne ki zarurat hai',
     'words': ['System', 'reboot', 'karne', 'ki', 'zarurat', 'hai'],
     'labels': ['ENG', 'ENG', 'URD', 'URD', 'URD', 'URD']},
    {'sentence': 'Mera assignment grade overall good aaya hai',
     'words': ['Mera', 'assignment', 'grade', 'overall', 'good', 'aaya', 'hai'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Group discussion active participation mangta hai',
     'words': ['Group', 'discussion', 'active', 'participation', 'mangta', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Fast internet speed makes life so easy',
     'words': ['Fast', 'internet', 'speed', 'makes', 'life', 'so', 'easy'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG']},
    {'sentence': 'Ghar ki lighting setup change kar di hai',
     'words': ['Ghar', 'ki', 'lighting', 'setup', 'change', 'kar', 'di', 'hai'],
     'labels': ['URD', 'URD', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Mera monthly expense budget control mein hai',
     'words': ['Mera', 'monthly', 'expense', 'budget', 'control', 'mein', 'hai'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Is song ki melody super relaxing hai',
     'words': ['Is', 'song', 'ki', 'melody', 'super', 'relaxing', 'hai'],
     'labels': ['URD', 'ENG', 'URD', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Online class joining link reset ho gaya',
     'words': ['Online', 'class', 'joining', 'link', 'reset', 'ho', 'gaya'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Weather shift bohot fast noticeable tha',
     'words': ['Weather', 'shift', 'bohot', 'fast', 'noticeable', 'tha'],
     'labels': ['ENG', 'ENG', 'URD', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Coffee roast profile perfect blend hai',
     'words': ['Coffee', 'roast', 'profile', 'perfect', 'blend', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD']},
    {'sentence': 'Mera gym membership renew karna padega',
     'words': ['Mera', 'gym', 'membership', 'renew', 'karna', 'padega'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Class test preparation on track chal rahi hai',
     'words': ['Class', 'test', 'preparation', 'on', 'track', 'chal', 'rahi', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Ghar mein tea break time fix hota hai',
     'words': ['Ghar', 'mein', 'tea', 'break', 'time', 'fix', 'hota', 'hai'],
     'labels': ['URD', 'URD', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'New project assignment submit karna hai',
     'words': ['New', 'project', 'assignment', 'submit', 'karna', 'hai'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Shopping list items buy kar liye hain',
     'words': ['Shopping', 'list', 'items', 'buy', 'kar', 'liye', 'hain'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'Mera phone storage full alert show kar raha hai',
     'words': ['Mera', 'phone', 'storage', 'full', 'alert', 'show', 'kar', 'raha', 'hai'],
     'labels': ['URD', 'ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']},
    {'sentence': 'System crash backup system ne save kar liya',
     'words': ['System', 'crash', 'backup', 'system', 'ne', 'save', 'kar', 'liya'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'ENG', 'URD', 'URD']},
    {'sentence': 'Online shopping delivery successful confirm ho gayi',
     'words': ['Online', 'shopping', 'delivery', 'successful', 'confirm', 'ho', 'gayi'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD']},
    {'sentence': 'Class lecture notes upload ho gaye hain',
     'words': ['Class', 'lecture', 'notes', 'upload', 'ho', 'gaye', 'hain'],
     'labels': ['ENG', 'ENG', 'ENG', 'ENG', 'URD', 'URD', 'URD']}
]

# Convert to flat CSV format required by the project
rows = []
for entry in data:
    for word, label in zip(entry['words'], entry['labels']):
        rows.append({
            'sentence': entry['sentence'],
            'word': word,
            'label': label
        })

# Create DataFrame and save CSV
df = pd.DataFrame(rows)
df.to_csv('dataset.csv', index=False, encoding='utf-8')

# Output verification
print("✅ Dataset CSV created successfully!")
print(f"📊 Total Word Entries: {len(df)}")
print(f"📝 Total Sentences: {df['sentence'].nunique()}")
print("\n🏷️ Label Distribution:")
print(df['label'].value_counts())

✅ Dataset CSV created successfully!
📊 Total Word Entries: 1333
📝 Total Sentences: 175

🏷️ Label Distribution:
label
ENG    799
URD    532
MIX      2
Name: count, dtype: int64

In [ ]:
# 1. Required libraries install karein
!pip install -q transformers torch datasets seqeval

import pandas as pd
import torch
from sklearn.model_selection import train_test_split

# Pehle CSV save karein (agar nahi bani hui)
if 'rows' in globals():
    df = pd.DataFrame(rows)
    df.to_csv('dataset.csv', index=False, encoding='utf-8')

# 2. Dataset load karein
df = pd.read_csv('dataset.csv')

# 3. Label Mappings (String -> ID and ID -> String)
label2id = {'URD': 0, 'ENG': 1, 'MIX': 2}
id2label = {0: 'URD', 1: 'ENG', 2: 'MIX'}

# 4. Words & Labels ko per sentence group karein
sentences = df.groupby('sentence').apply(
    lambda x: {'words': x['word'].tolist(), 'labels': x['label'].tolist()}
).tolist()

# 5. Dataset ko Train (80%) aur Test (20%) mein split karein
train_data, test_data = train_test_split(sentences, test_size=0.2, random_state=42)

print(f"Total Sentences: {len(sentences)}")
print(f"Training Sentences: {len(train_data)}")
print(f"Testing Sentences: {len(test_data)}")

Total Sentences: 175
Training Sentences: 140
Testing Sentences: 35

/tmp/ipykernel_2440/1457444442.py:21: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sentences = df.groupby('sentence').apply(

In [ ]:
from transformers import AutoTokenizer, AutoModelForTokenClassification, TrainingArguments, Trainer, DataCollatorForTokenClassification
from datasets import Dataset

# 1. Load Pretrained Tokenizer and Model
model_name = 'xlm-roberta-base'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    num_labels=3,
    id2label=id2label,
    label2id=label2id
)

# 2. Tokenize and Align Labels function
def tokenize_and_align_labels(examples):
    tokenized = tokenizer(examples['words'], truncation=True, is_split_into_words=True)
    labels = []

    for i, label in enumerate(examples['labels']):
        word_ids = tokenized.word_ids(batch_index=i)
        label_ids = []
        prev_word = None
        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != prev_word:
                label_ids.append(label2id[label[word_id]])
            else:
                label_ids.append(-100)
            prev_word = word_id
        labels.append(label_ids)

    tokenized['labels'] = labels
    return tokenized

# 3. Convert to HuggingFace Dataset Format
def to_hf_dataset(data):
    return Dataset.from_dict({
        'words': [d['words'] for d in data],
        'labels': [d['labels'] for d in data]
    })

train_ds = to_hf_dataset(train_data).map(tokenize_and_align_labels, batched=True)
test_ds = to_hf_dataset(test_data).map(tokenize_and_align_labels, batched=True)

# 4. Define Training Arguments
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=5,
    per_device_train_batch_size=16,
    eval_strategy='epoch',
    save_strategy='epoch',
    logging_steps=10,
    load_best_model_at_end=True
)

# 5. Initialize Trainer (processing_class updated)
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=test_ds,
    processing_class=tokenizer,
    data_collator=DataCollatorForTokenClassification(tokenizer)
)

# 6. Start Training
print("Starting training...")
trainer.train()
print("Training complete!")

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForTokenClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
classifier.weight           | MISSING    |
classifier.bias             | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/140 [00:00<?, ? examples/s]

Map:   0%|          | 0/35 [00:00<?, ? examples/s]

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training complete!

In [ ]:
!hf auth logout

Hint: A new version of huggingface_hub (1.27.0) is available! You are using version 1.23.0.
To update, run: hf update
Not logged in!

In [2]:
from huggingface_hub import notebook_login
notebook_login()

In [6]:
# ==============================================================================
# 1. Install & Imports
# ==============================================================================
!pip install -q transformers torch datasets seqeval huggingface_hub

import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)
from datasets import Dataset, load_dataset
from seqeval.metrics import classification_report

# ==============================================================================
# 2. Load Dataset Directly from HuggingFace
# ==============================================================================
print("📥 Loading dataset from HuggingFace Hub...")
hf_data = load_dataset("Ushna-Alam219/code-switching-codesaviours-si26-ushna")
df = hf_data['train'].to_pandas()

label2id = {'URD': 0, 'ENG': 1, 'MIX': 2}
id2label = {0: 'URD', 1: 'ENG', 2: 'MIX'}

# Group words and labels per sentence
sentences = df.groupby('sentence').apply(
    lambda x: {'words': x['word'].tolist(), 'labels': x['label'].tolist()}
).tolist()

# Train (80%) and Test (20%) Split
train_data, test_data = train_test_split(sentences, test_size=0.2, random_state=42)

print(f"✅ Total Sentences: {len(sentences)}")
print(f"✅ Training Sentences: {len(train_data)}")
print(f"✅ Testing Sentences: {len(test_data)}")

# ==============================================================================
# 3. Model & Tokenizer Initialization
# ==============================================================================
model_name = 'xlm-roberta-base'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    num_labels=3,
    id2label=id2label,
    label2id=label2id
)

# Tokenize and align labels
def tokenize_and_align_labels(examples):
    tokenized = tokenizer(examples['words'], truncation=True, is_split_into_words=True)
    labels = []
    for i, label in enumerate(examples['labels']):
        word_ids = tokenized.word_ids(batch_index=i)
        label_ids = []
        prev_word = None
        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != prev_word:
                label_ids.append(label2id[label[word_id]])
            else:
                label_ids.append(-100)
            prev_word = word_id
        labels.append(label_ids)
    tokenized['labels'] = labels
    return tokenized

def to_hf_dataset(data):
    return Dataset.from_dict({
        'words': [d['words'] for d in data],
        'labels': [d['labels'] for d in data]
    })

train_ds = to_hf_dataset(train_data).map(tokenize_and_align_labels, batched=True)
test_ds = to_hf_dataset(test_data).map(tokenize_and_align_labels, batched=True)

# ==============================================================================
# 4. Training
# ==============================================================================
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=5,
    per_device_train_batch_size=16,
    eval_strategy='epoch',
    save_strategy='epoch',
    logging_steps=10,
    load_best_model_at_end=True
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=test_ds,
    processing_class=tokenizer,
    data_collator=DataCollatorForTokenClassification(tokenizer)
)

print("\n🚀 Starting model training...")
trainer.train()
print("🎉 Training finished successfully!")

# ==============================================================================
# 5. Evaluation Report (F1-Scores)
# ==============================================================================
predictions, labels, _ = trainer.predict(test_ds)
predictions = np.argmax(predictions, axis=2)

true_labels = [[id2label[l] for l in label if l != -100] for label in labels]
pred_labels = [[id2label[p] for (p, l) in zip(prediction, label) if l != -100] for prediction, label in zip(predictions, labels)]

print("\n📊 --- EVALUATION REPORT (F1 SCORES) ---")
print(classification_report(true_labels, pred_labels))

# ==============================================================================
# 6. Push Model to Hugging Face Model Hub
# ==============================================================================
repo_name = "code-switching-codesaviours-si26-ushna"

print("\n📤 Uploading Model & Tokenizer to HuggingFace Model Hub...")
model.push_to_hub(repo_name)
tokenizer.push_to_hub(repo_name)

print(f"\n🌟 ALL DONE! Model successfully published at:")
print(f"https://huggingface.co/Ushna-Alam219/{repo_name}")

📥 Loading dataset from HuggingFace Hub...

README.md:   0%|          | 0.00/529 [00:00<?, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

dataset.csv:   0%|          | 0.00/74.0k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1333 [00:00<?, ? examples/s]

/tmp/ipykernel_1486/2225297979.py:31: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sentences = df.groupby('sentence').apply(

✅ Total Sentences: 175
✅ Training Sentences: 140
✅ Testing Sentences: 35

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.12GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForTokenClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/140 [00:00<?, ? examples/s]

Map:   0%|          | 0/35 [00:00<?, ? examples/s]

🚀 Starting model training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

🎉 Training finished successfully!

📊 --- EVALUATION REPORT (F1 SCORES) ---
              precision    recall  f1-score   support

          IX       0.00      0.00      0.00         1
          NG       0.99      1.00      0.99       150
          RD       0.96      0.98      0.97        55

   micro avg       0.98      0.99      0.99       206
   macro avg       0.65      0.66      0.66       206
weighted avg       0.98      0.99      0.98       206


📤 Uploading Model & Tokenizer to HuggingFace Model Hub...

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: ENG seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: URD seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: MIX seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...l0cjpq4/model.safetensors:   0%|          | 13.6kB / 1.11GB

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mp3y_go6oi/tokenizer.json: 100%|##########| 17.1MB / 17.1MB

🌟 ALL DONE! Model successfully published at:
https://huggingface.co/Ushna-Alam219/code-switching-codesaviours-si26-ushna